STORE_SRCS :=	../config.cpp	\
				../config_parser.cpp	\
				../location_config.cpp	\
				../parser_utils.cpp		\
				../server_config.cpp	\
				store.cpp 

ERROR_SRCS :=	../config.cpp	\
				../config_parser.cpp	\
				../location_config.cpp	\
				../parser_utils.cpp		\
				../server_config.cpp	\
				store.cpp 

store: $(STORE_SRCS)
	c++ -o a.out $^

error: $(ERROR_SRCS)
	c++ -o a.out $^

